<a href="https://colab.research.google.com/github/mpradeep2005/TensorFlow_Basics/blob/main/TensorFlow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
tensor_1=tf.constant(4)
print(tensor_1)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
tensor_2=tf.constant([2,3,4])
print(tensor_2)

tf.Tensor([2 3 4], shape=(3,), dtype=int32)


In [5]:
tensor_3=tf.constant(
    [[1,2,3],
     [4,2,5],
     [6,4,2]]
)
print(tensor_3)

tf.Tensor(
[[1 2 3]
 [4 2 5]
 [6 4 2]], shape=(3, 3), dtype=int32)


In [6]:
tensor_4=tf.constant(
     [[[1,2,3],
     [4,2,5],
     [6,4,2]],
    [[1,2,3],
     [4,2,5],
     [6,4,2]],
    [[1,2,3],
     [4,2,5],
     [6,4,2]],
    [[1,2,3],
     [4,2,5],
     [6,4,2]]]
)
print(tensor_4)

tf.Tensor(
[[[1 2 3]
  [4 2 5]
  [6 4 2]]

 [[1 2 3]
  [4 2 5]
  [6 4 2]]

 [[1 2 3]
  [4 2 5]
  [6 4 2]]

 [[1 2 3]
  [4 2 5]
  [6 4 2]]], shape=(4, 3, 3), dtype=int32)
